// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd80GUFi6-JF8gO7RVfqU6E4QiVHG3UAU',
    appId: '1:497245437485:web:b63de2ca017d630c1642a4',
    messagingSenderId: '497245437485',
    projectId: 'ucua-mobile-app-848d3',
    authDomain: 'ucua-mobile-app-848d3.firebaseapp.com',
    storageBucket: 'ucua-mobile-app-848d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfIn_iOsHDo_F_FbxtJe3ITZANM-YVYX0',
    appId: '1:497245437485:android:cf5ddac29ca689bc1642a4',
    messagingSenderId: '497245437485',
    projectId: 'ucua-mobile-app-848d3',
    storageBucket: 'ucua-mobile-app-848d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzHNTBs07QP9orBNTrw6Cy9VLRXOW6h7I',
    appId: '1:497245437485:ios:cb5c1d89450ff16c1642a4',
    messagingSenderId: '497245437485',
    projectId: 'ucua-mobile-app-848d3',
    storageBucket: 'ucua-mobile-app-848d3.appspot.com',
    iosBundleId: 'com.example.latestucua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzHNTBs07QP9orBNTrw6Cy9VLRXOW6h7I',
    appId: '1:497245437485:ios:cb5c1d89450ff16c1642a4',
    messagingSenderId: '497245437485',
    projectId: 'ucua-mobile-app-848d3',
    storageBucket: 'ucua-mobile-app-848d3.appspot.com',
    iosBundleId: 'com.example.latestucua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd80GUFi6-JF8gO7RVfqU6E4QiVHG3UAU',
    appId: '1:497245437485:web:72102e3be3c65b931642a4',
    messagingSenderId: '497245437485',
    projectId: 'ucua-mobile-app-848d3',
    authDomain: 'ucua-mobile-app-848d3.firebaseapp.com',
    storageBucket: 'ucua-mobile-app-848d3.appspot.com',
  );

}